#################
# ParallelUtils #
#################

# Debug=1, Info=2, Warning=3, Error=4
debug: 2

# mySQL connection info
sql:
  # Database info
  address: example.com:7000
  database: databaseName
  username: user
  password: pass

# Discord Bot Integration
token: discordApiToken
staff_channel_id: staffChannelId
vp_message_channel: discordVotePartyMessageChannel
vp_message_id: discordVotePartyMessageId
server_id: discordServerId
staff_id: discordStaffRoleId

# Github integration for version checking
github_token: githubApiToken

# Sunken Treasure
treasure_loot: sunkenTreasureLootTable