#################
# ParallelUtils #
#################

# Debug=1, Info=2, Warning=3, Error=4
debug: 2

# mySQL connection info
sql:
  # JDBC Connection String (USE EITHER JDBC OR THE DATABASE INFO BELOW)
  jdbc: jdbc:mysql://example.com/databaseName
  # Database info
  address: example.com:7000
  database: databaseName
  username: user
  password: pass

# Discord Bot Integration
token:
staff_channel_id:
server_id:
staff_id:

# Github integration for version checking
github_token:

# Sunken Treasure
treasure_loot: