name: Parallelutils
version: ${project.version}
main: parallelmc.parallelutils.Parallelutils
api-version: 1.17
authors: [Jake, Evelyn]
description: A plugin containing miscellaneous features and changes for play.parallel.ga
depend: [PlaceholderAPI]
softdepend: [Multiverse-Core, FractalForest, WorldGuard, VoteParty, FrozenJoin]
commands:
  parallelutils:
    description: Get information about the plugin
    usage: /parallelutils
    permission-message: You do not have permission
  pu:
    description: Get information about the plugin
    usage: /pu
    permission-message: You do not have permission
  depositexp:
    description: Deposit exp into the player's ender chest
    usage: /depositexp <amount | all>
    permission-message: You do not have permission
  withdrawexp:
    description: Withdraw exp from the player's ender chest
    usage: /withdrawexp <amount | all>
    permission-message: You do not have permission
permissions:
  parallelutils.*:
    description: Gives access to all PU commands
    children:
      parallelutils.basic: true
      parallelutils.test: true
      parallelutils.spawn: true
      parallelutils.help: true
    default: false
  parallelutils.basic:
    description: Gives access to any PU commands. Required to do anything
    children:
      parallelutils.help: true
    default: false
  parallelutils.spawn:
    description: Gives access to spawning commands, such as summoning and monster spawners.
    children:
      parallelutils.spawn.summon: true
      parallelutils.spawn.spawners: true
    default: false
  parallelutils.spawn.summon:
    description: Gives access to spawn summon command.
    default: false
  parallelutils.spawn.spawners:
    description: Gives access to commands involving spawners.
    children:
      parallelutils.spawn.spawners.create: true
      parallelutils.spawn.spawners.list: true
      parallelutils.spawn.spawners.delete: true
    default: false
  parallelutils.spawn.spawners.create:
    description: Gives access to creating spawners.
    default: false
  parallelutils.spawn.spawners.list:
    description: Gives access to listing spawners
    default: false
  parallelutils.spawn.spawners.delete:
    description: Gives access to deleting spawners.
    default: false
  parallelutils.give:
    description: Gives access to giving ParallelItems.
    default: false
  parallelutils.test:
    description: Gives access to the test command
    default: false
  parallelutils.help:
    description: Gives access to the help command
    default: false
  parallelutils.effects:
    description: Gives access to effects debug command
    default: false
